AWSTemplateFormatVersion: '2010-09-09'
Description: My first serverless application.
Resources:
  Emails:
    Properties:
      CodeUri: s3://email-generator-lamda/a86bb17c3b281d25cb8c39c7f8dc62f4
      Environment:
        Variables:
          AZURE_STORAGE_CONNECTION_STRING: null
          CRHONOPIN_SMTP_PASSWORD: null
      Events:
        CreateEmail:
          Properties:
            Method: post
            Path: /email
          Type: Api
        GetEmail:
          Properties:
            Method: get
            Path: /email
          Type: Api
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
