AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first serverless application.

Resources:

  Emails:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10
      Environment:
        Variables:
          CRHONOPIN_SMTP_PASSWORD:
          AZURE_STORAGE_CONNECTION_STRING:
      Events:
        Email:
          Type: Api
          Properties:
            Path: /email
            Method: get
        # CreateProduct:
        #   Type: Api
        #   Properties:
        #     Path: /email
        #     Method: post
        # Product:
        #   Type: Api
        #   Properties:
        #     Path: /email/{email}
        #     Method: any