AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first serverless application.

Resources:

  Emails:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10
      Environment:
        Variables:
          CRHONOPIN_SMTP_PASSWORD: If641812!@
          AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=chronopin;AccountKey=S61x+kGTBaVbcGhMveyLXFFRFdg8V8xOr+saHi/bOWAeUYUZqe67TruW7cpseSH2qiQxd6dzMNqzmJ8i7nvdHw==
      Events:
        Email:
          Type: Api
          Properties:
            Path: /email
            Method: get
        # CreateProduct:
        #   Type: Api
        #   Properties:
        #     Path: /email
        #     Method: post
        # Product:
        #   Type: Api
        #   Properties:
        #     Path: /email/{email}
        #     Method: any